spring:
  application:
    name: CoCoDa
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: ""
#    username: ""
#    password: ""

#mybatis:
#  mapper-locations: classpath:mapper/*.xml