spring:
  application:
    name: CoCoDa

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.2:1521:XE
    username: hr
    password: hr

mybatis:
  mapper-locations: classpath:mapper/*.xml