spring:
  application:
    name: CoCoDa
  #autoconfigure:
    #exclude:
    #  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    #  - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://''/''?useSSL=false&allowPublicKeyRetrieval=true
    username: ''
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create # 실서버는 validate로 재설정 필요
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  #config-location: classpath:mybatis-config.xml
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.CoCoDa.repository

