spring:
  application:
    name: CoCoDa

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ""
    username: ""
    password: ""

mybatis:
  mapper-locations: classpath:mapper/*.xml